---
# roles/nginx_proxy/handlers/main.yml

- name: Restart nginx
  ansible.builtin.command: pct exec {{ container.vmid }} -- systemctl restart nginx
  listen: nginx_restart
  changed_when: false

- name: Reload nginx
  ansible.builtin.command: pct exec {{ container.vmid }} -- systemctl reload nginx
  listen: nginx_reload
  changed_when: false
