---
# roles/netbox_app/handlers/main.yml

- name: Restart NetBox
  ansible.builtin.command: pct exec {{ container.vmid }} -- systemctl restart netbox
  listen: netbox_restart
  changed_when: false

- name: Reload NetBox
  ansible.builtin.command: pct exec {{ container.vmid }} -- systemctl reload netbox
  listen: netbox_reload
  changed_when: false

- name: Restart NetBox RQ
  ansible.builtin.command: pct exec {{ container.vmid }} -- systemctl restart netbox-rq
  listen: netbox_rq_restart
  changed_when: false
  failed_when: false
