---
# Proxmox Container Role - Galaxy Metadata
galaxy_info:
  role_name: proxmox_container
  author: NetBox Proxmox Team
  description: Generic LXC container creation and management for Proxmox VE
  company: ""
  license: MIT
  min_ansible_version: "2.17"

  platforms:
    - name: Proxmox
      versions:
        - "9"
        - "8"
    - name: Debian
      versions:
        - trixie
        - bookworm

  galaxy_tags:
    - proxmox
    - container
    - lxc
    - virtualization

dependencies:
  - role: proxmox_network
